# Generated by Django 3.0.3 on 2020-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
    ]
